### ISSUE TITLE
AOT build failing! Team can you please check this??

### ISSUE THREAD

**Issue by Chethannp** [uploadcare/ngx-uploadcare-widget#17]
Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are
            not supported. Consider replacing the function or lambda with a reference to an exported function, resolving
            symbol Component in
            C:/Users/Chethan/Music/flockby-ui/node_modules/ngx-uploadcare-widget/node_modules/@angular/core/core.d.ts,
            resolving symbol UcWidgetComponent in
            C:/Users/Chethan/Music/flockby-ui/node_modules/ngx-uploadcare-widget/release/ucWidget/ucWidget.component.d.ts,
            resolving symbol UcWidgetComponent in
            C:/Users/Chethan/Music/flockby-ui/node_modules/ngx-uploadcare-widget/release/ucWidget/ucWidget.component.d.ts
![2018_07_25_00_11_44_npm](https://user-images.githubusercontent.com/7566931/43159261-807aa258-8f9f-11e8-8072-cd11120f45e6.png)

**Comment by Chethannp** [comment]
@Zmoki , @ZNick1982  - can you please check is asap please.....!
![2018_07_25_00_11_44_npm](https://user-images.githubusercontent.com/7566931/43159626-80801f84-8fa0-11e8-91a0-d891bd8cffe4.png)

**Comment by ZNick1982** [comment]
Hi @Chethannp .
I work on this issue.
I will write back with updates.

**Comment by Chethannp** [comment]
Hope to see some update as soon as possible. Not able to release our app :(

**Comment by Chethannp** [comment]
Also on safari browser the uploadcare widget displays a white screen.

**Comment by Chethannp** [comment]
@Zmoki , @ZNick1982 
Team any update on this?? Its becoming critical for us with uploadcare dependency, requesting you to please provide a solution asap!

**Comment by ZNick1982** [comment]
Hi @Chethannp  I did try AOT compilation on 5.x and 6.x versions of Angular with Angular cli and its works fine.
For this I used branch: https://github.com/uploadcare/ngx-uploadcare-widget/tree/APP_VERSION_Fix
Its also looks like that error is Ionic related.
Can you please prepare simple example with this error and put it on github? So, I can simple reproduce it then.

**Comment by Chethannp** [comment]
Let me try the above mentioned code available in that branch and will share a new ionic sample code or steps

**Comment by Chethannp** [comment]
I still get this error while using UcWidgetModule 

ERROR Error: Uncaught (in promise): Error: Unexpected module 'UcWidgetModule' declared by the module 'ComponentsModule'. Please add a @Pipe/@Directive/@Component annotation.
Error: Unexpected module 'UcWidgetModule' declared by the module 'ComponentsModule'. Please add a @Pipe/@Directive/@Component annotation.
    at syntaxError (compiler.js:466)
    at compiler.js:15136
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15118)
    at CompileMetadataResolver.getNgModuleSummary (compiler.js:14998)
    at compiler.js:15086
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15071)
    at JitCompiler._loadModules (compiler.js:33484)
    at JitCompiler._compileModuleAndComponents (compiler.js:33445)
    at syntaxError (compiler.js:466)
    at compiler.js:15136
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15118)
    at CompileMetadataResolver.getNgModuleSummary (compiler.js:14998)
    at compiler.js:15086
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15071)
    at JitCompiler._loadModules (compiler.js:33484)
    at JitCompiler._compileModuleAndComponents (compiler.js:33445)
    at c (polyfills.js:3)
    at Object.reject (polyfills.js:3)
    at NavControllerBase._fireError (nav-controller-base.js:223)
    at NavControllerBase._failed (nav-controller-base.js:216)
    at nav-controller-base.js:263
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4626)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
defaultErrorLogger @ core.js:1350
ErrorHandler.handleError @ core.js:1411
IonicErrorHandler.handleError @ ionic-error-handler.js:61
next @ core.js:5373
schedulerFn @ core.js:4220
SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ core.js:4200
(anonymous) @ core.js:4648
t.invoke @ polyfills.js:3
r.run @ polyfills.js:3
NgZone.runOutsideAngular @ core.js:4574
onHandleError @ core.js:4648
t.handleError @ polyfills.js:3
r.runGuarded @ polyfills.js:3
(anonymous) @ polyfills.js:3
n.microtaskDrainDone @ polyfills.js:3
o @ polyfills.js:3
Promise.then (async)
r @ polyfills.js:3
t.scheduleTask @ polyfills.js:3
onScheduleTask @ polyfills.js:3
t.scheduleTask @ polyfills.js:3
r.scheduleTask @ polyfills.js:3
r.scheduleMicroTask @ polyfills.js:3
f @ polyfills.js:3
c @ polyfills.js:3
(anonymous) @ polyfills.js:3
webpackJsonpCallback @ bootstrap c91b85bdb890fc871649:21
(anonymous) @ 0.js:1

**Comment by Chethannp** [comment]
Prod build error details

`E:\uploadcare (master -> origin)                                                                                                  
λ ionic build --prod                                                                                                              
[INFO] Running app-scripts build: --prod                                                                                          
                                                                                                                                  
[23:50:08]  build prod started ...                                                                                                
[23:50:08]  clean started ...                                                                                                     
[23:50:08]  clean finished in 6 ms                                                                                                
[23:50:08]  copy started ...                                                                                                      
[23:50:08]  deeplinks started ...                                                                                                 
[23:50:08]  deeplinks finished in 17 ms                                                                                           
[23:50:08]  ngc started ...                                                                                                       
[23:50:13]  ngc finished in 4.74 s                                                                                                
[23:50:13]  preprocess started ...                                                                                                
[23:50:13]  preprocess finished in 1 ms                                                                                           
[23:50:13]  webpack started ...                                                                                                   
[23:50:13]  copy finished in 4.97 s                                                                                               
Error: ./node_modules/tslib/tslib.es6.js                                                                                          
Module build failed: TypeError: Cannot read property 'type' of undefined                                                          
    at Object.getEffectiveTypeAnnotationNode (E:\uploadcare\node_modules\typescript\lib\typescript.js:9341:18)                    
    at assignContextualParameterTypes (E:\uploadcare\node_modules\typescript\lib\typescript.js:41652:25)                          
    at checkFunctionExpressionOrObjectLiteralMethod (E:\uploadcare\node_modules\typescript\lib\typescript.js:41948:29)            
    at checkExpressionWorker (E:\uploadcare\node_modules\typescript\lib\typescript.js:42959:28)                                   
    at checkExpression (E:\uploadcare\node_modules\typescript\lib\typescript.js:42898:42)                                         
    at checkBinaryLikeExpression (E:\uploadcare\node_modules\typescript\lib\typescript.js:42475:29)                               
    at checkBinaryExpression (E:\uploadcare\node_modules\typescript\lib\typescript.js:42467:20)                                   
    at checkExpressionWorker (E:\uploadcare\node_modules\typescript\lib\typescript.js:42980:28)                                   
    at checkExpression (E:\uploadcare\node_modules\typescript\lib\typescript.js:42898:42)                                         
    at checkBinaryLikeExpression (E:\uploadcare\node_modules\typescript\lib\typescript.js:42475:29)                               
 @ ./node_modules/@angular/platform-browser/esm5/platform-browser.js 9:0-44                                                       
 @ ./src/app/main.ts,./src/app/main.ts                                                                                            
Module not found: Error: Can't resolve './app.module.ngfactory' in 'E:\uploadcare\src\app'                                        
resolve './app.module.ngfactory' in 'E:\uploadcare\src\app'                                                                       
  using description file: E:\uploadcare\package.json (relative path: ./src/app)                                                   
    Field 'browser' doesn't contain a valid alias configuration                                                                   
  after using description file: E:\uploadcare\package.json (relative path: ./src/app)                                             
    using description file: E:\uploadcare\package.json (relative path: ./src/app/app.module.ngfactory)                            
      no extension                                                                                                                
        Field 'browser' doesn't contain a valid alias configuration                                                               
        E:\uploadcare\src\app\app.module.ngfactory doesn't exist                                                                  
      .ts                                                                                                                         
        Field 'browser' doesn't contain a valid alias configuration                                                               
        E:\uploadcare\src\app\app.module.ngfactory.ts doesn't exist                                                               
      .js                                                                                                                         
        Field 'browser' doesn't contain a valid alias configuration                                                               
        E:\uploadcare\src\app\app.module.ngfactory.js doesn't exist                                                               
      .json                                                                                                                       
        Field 'browser' doesn't contain a valid alias configuration                                                               
        E:\uploadcare\src\app\app.module.ngfactory.json doesn't exist                                                             
      as directory                                                                                                                
        E:\uploadcare\src\app\app.module.ngfactory doesn't exist                                                                  
[E:\uploadcare\src\app\app.module.ngfactory]                                                                                      
[E:\uploadcare\src\app\app.module.ngfactory.ts]                                                                                   
[E:\uploadcare\src\app\app.module.ngfactory.js]                                                                                   
[E:\uploadcare\src\app\app.module.ngfactory.json]                                                                                 
[E:\uploadcare\src\app\app.module.ngfactory]                                                                                      
 @ ./src/app/main.ts 2:0-60                                                                                                       `

**Comment by Chethannp** [comment]
Let me know if you want to do a Skype / Hangout call if you are around will send you my id.

**Comment by ZNick1982** [comment]
Thanks @Chethannp .
I will try and write back as soon as check this.

**Comment by Chethannp** [comment]
Sure thanks!

**Comment by Chethannp** [comment]
![2018_07_25_00_11_44_npm](https://user-images.githubusercontent.com/7566931/43281743-1241965e-9132-11e8-82aa-58c36865c213.png)

Tried to create a new Angular project installed uploadcare, imported it to app.module.ts file and tried to run ng serve --open and I am getting the above error.
This is on angular project

**Comment by Chethannp** [comment]
![2018_07_25_00_11_44_npm](https://user-images.githubusercontent.com/7566931/43282019-b95e2204-9132-11e8-80a2-70b305759453.png)

**Comment by ZNick1982** [comment]
Can you describe the steps how did you create the app?
Because the errors related to absent of rxjs module in Angular, widget module is not include this also and  don't use it.

**Comment by Chethannp** [comment]
1. npm install -g @angular/cli
2. ng new my-app
3. cd my-app
4. npm install ngx-uploadcare-widget
5. App.module.ts file -->
 import { UcWidgetComponent } from 'ngx-uploadcare-widget';
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    UcWidgetComponent
  ],
  providers: [],
  bootstrap: [AppComponent]
})
6. ng serve --open

**Comment by ZNick1982** [comment]
Thanks, will check this also.

**Comment by Chethannp** [comment]
But please try to get this working on Ionic project first :)

**Comment by Chethannp** [comment]
@ZNick - can you update on this please.

**Comment by ZNick1982** [comment]
I reproduced both errors: on Angular and IONIC.
Still working on it.

**Comment by Chethannp** [comment]
Oki cool...! Hope you find a solution at the earliest :)

**Comment by ZNick1982** [comment]
Yes I fixed it.
Created pr https://github.com/uploadcare/ngx-uploadcare-widget/pull/18
Requested the review.

**Comment by Chethannp** [comment]
Awesome thank you. Will check and let you know!

**Comment by Chethannp** [comment]
@Zmoki - Can you please review this and merge this pull request from @ZNick1982, we are eagerly waiting to test this and praying it solves our problem :).... Also @ZNick1982 - I would request you to please update on the readme docs on the usage.

Thanks!

**Comment by Chethannp** [comment]
![a8d1d819-31f5-4de3-9235-b8dd5b520204](https://user-images.githubusercontent.com/7566931/43369016-0317b8f8-9384-11e8-8de2-3b1052b9e5c3.png)

As shown in the screenshot there is a white screen display but clicking on it open facebook auth.

**Comment by Chethannp** [comment]
APP_Version issue has come back again, I am requesting the entire team to please give a confirmation on proper working of this module.

**Comment by Chethannp** [comment]
With this latest fix the AOT Build is also failing

**Comment by Chethannp** [comment]
Still have to follow #10 to fix the Aot problem

**Comment by Chethannp** [comment]
![2018_08_06_00_13_25_films_tv](https://user-images.githubusercontent.com/7566931/43688817-bf701804-990d-11e8-8bc2-5c6bd930f0c8.png)

**Comment by bautrukevich** [comment]
@ZNick1982 can you check, please?

**Comment by ZNick1982** [comment]
Hi @Chethannp. Can you try following:
1. Delete folder ngx-uploadcare-widget from node_modules.
2. Install ngx-uploadcare-widget again via: `npm install ngx-uploadcare-widget --save-dev`.
3. Try to run: `ionic build --prod` or `ionic serve`

I did the same actions for my test ionic app and its works fine.
Here is my console log:
```
PS C:\Projects\other\uploadcare\IONIC error\testApp> npm install ngx-uploadcare-widget
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ ngx-uploadcare-widget@1.1.0
added 1 package and audited 3537 packages in 13.377s
found 0 vulnerabilities

PS C:\Projects\other\uploadcare\IONIC error\testApp> ionic build --prod
> ionic-app-scripts build --prod
[12:56:47]  ionic-app-scripts 3.1.11
[12:56:47]  build prod started ...
(node:22732) ExperimentalWarning: The fs.promises API is experimental
[12:56:47]  clean started ...
[12:56:47]  clean finished in 8 ms
[12:56:47]  copy started ...
[12:56:47]  deeplinks started ...
[12:56:47]  deeplinks finished in 14 ms
[12:56:47]  ngc started ...
[12:57:01]  ngc finished in 14.38 s
[12:57:01]  preprocess started ...
[12:57:01]  preprocess finished in 1 ms
[12:57:01]  webpack started ...
[12:57:02]  copy finished in 15.27 s
[12:57:35]  webpack finished in 33.88 s
[12:57:35]  uglify started ...
[12:57:35]  sass started ...
(node:28276) ExperimentalWarning: The fs.promises API is experimental
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[12:57:39]  sass finished in 3.22 s
[12:57:39]  cleancss started ...
(node:22672) ExperimentalWarning: The fs.promises API is experimental
[12:57:41]  cleancss finished in 2.56 s
[12:57:56]  uglify finished in 20.46 s
[12:57:56]  postprocess started ...
[12:57:56]  postprocess finished in 18 ms
[12:57:56]  lint started ...
[12:57:56]  build prod finished in 68.96 s
(node:24336) ExperimentalWarning: The fs.promises API is experimental
[12:58:00]  lint finished in 4.08 s
PS C:\Projects\other\uploadcare\IONIC error\testApp>
```

**Comment by Chethannp** [comment]
![2018_08_09_22_35_28_npm](https://user-images.githubusercontent.com/7566931/43914188-c71bb882-9c24-11e8-8f15-80aac2288a74.png)

**Comment by bautrukevich** [comment]
@Chethannp AOT building is working now? Can we close this issue?

**Comment by Chethannp** [comment]
Thank you team for the help.. AOT build is working fine now. Will close this issue. Thanks again!
